apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-bff
  annotations: 
    assetid: example-bff
    github-squad: icis-mars
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
  definition: |
    syntax = "proto3";

    service Exampler {
      rpc Example (ExampleMessage) returns (ExampleMessage) {};
    }

    message ExampleMessage {
      string example = 1;
    };

