apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: bff-domain
  description: BFF domain
  annotations: 
    assetid: top-level-domain
    github-squad: icis-mars
spec:
  type: service
  owner: user:aurorasean
  lifecycle: experimental

---

apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: canvas
  description: canvas
  annotations: 
    assetid: top-level-asset
    github-squad: icis-mars
spec:
  type: service
  owner: user:aurorasean
  lifecycle: experimental
  domain: bff-domain

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-bff
  description: example bff
  annotations: 
    assetid: example-bff
    github-squad: icis-mars
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
  system: canvas
  providesApis: [example-grpc-api]
  dependsOn:
    - resource:example-db

---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: example-bff-api
  description: example bff api
spec:
  type: bff-api
  lifecycle: experimental
  owner: user:guest
  system: canvas
  definition: |
    syntax = "python";
    import grpc
    import example_pb2_grpc 
    print("Hello world")

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: example-db
  description: example bff db
spec:
  type: mongo-database
  owner: user:guest
  system: canvas
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: example-bff-authoring-staging-deployment
  description: example bff db
spec:
  type: mongo-database
  owner: user:guest
  system: canvas